//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerQuest.Functions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeerQuest.Functions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;name&quot;,&quot;category&quot;,&quot;url&quot;,&quot;date&quot;,&quot;excerpt&quot;,&quot;thumbnail&quot;,&quot;lat&quot;,&quot;lng&quot;,&quot;address&quot;,&quot;phone&quot;,&quot;twitter&quot;,&quot;stars_beer&quot;,&quot;stars_atmosphere&quot;,&quot;stars_amenities&quot;,&quot;stars_value&quot;,&quot;tags&quot;
        ///&quot;...escobar&quot;,&quot;Closed venues&quot;,&quot;http://leedsbeer.info/?p=765&quot;,&quot;2012-11-30T21:58:52+00:00&quot;,&quot;...It&apos;s really dark in here!&quot;,&quot;http://leedsbeer.info/wp-content/uploads/2012/11/20121129_185815.jpg&quot;,&quot;53.8007317&quot;,&quot;-1.5481764&quot;,&quot;23-25 Great George Street, Leeds LS1 3BB&quot;,&quot;0113 220 4389&quot;,&quot;EscobarLeeds&quot;,&quot;2&quot;,&quot;3&quot;,&quot;3&quot;,&quot;3&quot;,&quot;food,live music,sofas&quot;
        ///&quot;&quot;&quot;Golf&quot;&quot; Cafe B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string leedsbeerquest {
            get {
                return ResourceManager.GetString("leedsbeerquest", resourceCulture);
            }
        }
    }
}
